#-------------------------------
# General Site Settings
title: Jacob Scott
logo: # You can add own logo. For example '/images/logo.png'.
description: Data Science & ML blog and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jacobscott.io" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Jacob Scott
  bio: I'm an analytics and machine learning professional, who's found his niche in the medtech industry.
  avatar: '/images/me_clipped.png'

social:
- {icon: "ion-logo-linkedin", label: LinkedIn, link: "https://www.linkedin.com/in/jacob-scott-171264160/"}
- {icon: "ion-logo-github", label: Github, link: "https://github.com/Jacob-A-Scott"}
- {icon: "ion-md-mail", label: Email, link: "mailto:jacobscott8910@gmail.com"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Hey, I'm Jacob!<br>Data Science Professional.
  hero__description: I'm an analytics and data science practitioner with a soft spot for visual design. Enthusiastic about health, technology, and solving tricky problems.
  hero__image: '/images/me_clipped.png'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: false # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title:  # Add your Title
mailchimp__text: # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: jacobscott8910@gmail.com # Add your email for contact form
  description: Reach out for info or to collaborate! I'm not looking for a job at the moment, but I'm always happy to connect.
  # formspree: https://formspree.io/f/xqkvovqa
# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed